## ================= Search =================
# the fields to return in search results from a solr query
# ontology search: if you define a value, ensure ontologyType is also included
search:
  external:
    filterConfigs:
      - signature: aspect
        execution: JOIN
        properties: {fromTable: ontology, fromAttribute: id_join, toTable: annotation, toAttribute: goId_join}
      - signature: usageIds,usageRelationships,descendants
        execution: REST_COMM
        properties: {
          ip: "http://ves-hx-c2:8082",
          resourceFormat: "/QuickGO/services/go/terms/{usageIds}/descendants?relations={usageRelationships}",
          responseClass: "uk.ac.ebi.quickgo.annotation.service.comm.rest.ontology.model.ConvertedOntologyFilter",
          responseConverter: "uk.ac.ebi.quickgo.annotation.service.comm.rest.ontology.converter.DescendantsFilterConverter"
        }
      - signature: usageIds,usageRelationships,slim
        execution: REST_COMM
        properties: {
          ip: "http://ves-hx-c2:8082",
          resourceFormat: "/QuickGO/services/go/terms/{usageIds}/descendants?relations={usageRelationships}",
          responseClass: "uk.ac.ebi.quickgo.annotation.service.comm.rest.ontology.model.ConvertedOntologyFilter",
          responseConverter: "uk.ac.ebi.quickgo.annotation.service.comm.rest.ontology.converter.SlimmingFilterConverter"
        }
model:
  repo2domainFieldNameTransformations:
    transformations: {
      goId_join: goId
    }
