## ================= Searching for preset relevancy =================
search:
  external:
    filterConfigs:
      - signature: assignedBy
        execution: REST_COMM
        properties: {
          ip: "http://ves-hx-c7:8090",
          resourceFormat: "/solr/annotation/terms?q=*%3A*&wt=json&indent=true&terms.fl=assignedBy",
          responseClass: "uk.ac.ebi.quickgo.client.service.loader.presets.RelevancyResponseType",
          responseConverter: "uk.ac.ebi.quickgo.client.service.loader.presets.RelevancyResponseConverter"
        }
      - signature: taxonId
        execution: REST_COMM
        properties: {
          ip: "http://ves-hx-c7:8090",
          resourceFormat: "/solr/annotation/terms?q=*%3A*&wt=json&indent=true&terms.fl=taxonId",
          responseClass: "uk.ac.ebi.quickgo.client.service.loader.presets.RelevancyResponseType",
          responseConverter: "uk.ac.ebi.quickgo.client.service.loader.presets.RelevancyResponseConverter"
        }
      - signature: qualifier
        execution: REST_COMM
        properties: {
          ip: "http://ves-hx-c7:8090",
          resourceFormat: "/solr/annotation/terms?q=*%3A*&wt=json&indent=true&terms.fl=qualifier",
          responseClass: "uk.ac.ebi.quickgo.client.service.loader.presets.RelevancyResponseType",
          responseConverter: "uk.ac.ebi.quickgo.client.service.loader.presets.RelevancyResponseConverter"
        }
cors:
  filters:
    - allow-origins: "http://www.ebi.ac.uk, http://wwwdev.ebi.ac.uk, http://localhost"
      path: "/**"